# Generated by Django 3.0.4 on 2020-07-04 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoInternaut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valide', models.BooleanField(default=False)),
                ('supprime', models.BooleanField(default=False)),
                ('vu', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.CharField(max_length=20)),
                ('media', models.FileField(default=None, null=True, upload_to='')),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='video', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
