# Generated by Django 3.0.4 on 2020-06-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoInternaut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valide', models.BooleanField(default=False)),
                ('supprime', models.BooleanField(default=False)),
                ('vu', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('titre', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('video', models.FileField(upload_to='')),
            ],
        ),
    ]
