# Generated by Django 3.0.4 on 2020-07-04 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_videointernaut_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videointernaut',
            name='description',
        ),
    ]
