# Generated by Django 3.0.4 on 2020-07-04 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_remove_videointernaut_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videointernaut',
            old_name='titre',
            new_name='commentaire',
        ),
    ]
