# Generated by Django 3.0.4 on 2020-07-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20200704_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videointernaut',
            name='video',
        ),
        migrations.AddField(
            model_name='videointernaut',
            name='media',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
    ]
