# Generated by Django 3.0.4 on 2020-07-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proprio', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=50)),
                ('valide', models.BooleanField(default=False)),
                ('supprime', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VideoYoutube',
            fields=[
                ('valide', models.BooleanField(default=False)),
                ('supprime', models.BooleanField(default=False)),
                ('titre', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('url', models.URLField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleSearchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valide', models.BooleanField(default=False)),
                ('supprime', models.BooleanField(default=False)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('date', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('url',)},
            },
        ),
    ]
