# Generated by Django 3.0.4 on 2020-06-25 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweets',
            name='url',
        ),
    ]
