# Generated by Django 3.0.4 on 2020-07-01 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoyoutube',
            name='titre',
            field=models.TextField(),
        ),
    ]
