# Generated by Django 3.0.4 on 2020-07-01 23:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0002_auto_20200701_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoyoutube',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
