# Generated by Django 3.0.4 on 2020-06-24 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0002_auto_20200622_1632'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='googlesearchresult',
            unique_together={('url',)},
        ),
    ]
