# Generated by Django 3.0.4 on 2020-06-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0002_remove_tweets_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='date',
            field=models.CharField(max_length=50),
        ),
    ]
