# Generated by Django 3.0.4 on 2020-06-25 03:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0003_auto_20200624_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoyoutube',
            name='id',
        ),
        migrations.AddField(
            model_name='videoyoutube',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videoyoutube',
            name='titre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='videoyoutube',
            name='url',
            field=models.URLField(primary_key=True, serialize=False),
        ),
    ]
