# Generated by Django 3.0.4 on 2020-06-25 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0004_auto_20200625_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoyoutube',
            name='titre',
            field=models.CharField(max_length=1000),
        ),
    ]
