# Generated by Django 3.0.4 on 2020-06-25 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0005_auto_20200625_0452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoyoutube',
            name='date',
        ),
    ]
