# Generated by Django 3.0.4 on 2020-06-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField(max_length=20)),
                ('suspect', models.IntegerField()),
                ('confirme', models.IntegerField()),
                ('critique', models.IntegerField()),
                ('mort', models.IntegerField()),
                ('guerie', models.IntegerField()),
            ],
        ),
    ]
