# Generated by Django 3.0.4 on 2020-06-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suspect', models.IntegerField()),
                ('confirme', models.IntegerField()),
                ('critique', models.IntegerField()),
                ('mort', models.IntegerField()),
                ('guerie', models.IntegerField()),
                ('degre', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('valide', models.BooleanField(default=False)),
                ('supprime', models.BooleanField(default=False)),
                ('vu', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='region',
            name='confirme',
        ),
        migrations.RemoveField(
            model_name='region',
            name='critique',
        ),
        migrations.RemoveField(
            model_name='region',
            name='guerie',
        ),
        migrations.RemoveField(
            model_name='region',
            name='mort',
        ),
        migrations.RemoveField(
            model_name='region',
            name='suspect',
        ),
        migrations.AddField(
            model_name='region',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='region',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
