# Generated by Django 3.0.4 on 2020-06-05 17:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='date_validation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='degre',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='region',
            name='confirme',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='region',
            name='critique',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='region',
            name='guerie',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='region',
            name='mort',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='region',
            name='suspect',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='HistoriqueRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suspect', models.IntegerField(default=0)),
                ('confirme', models.IntegerField(default=0)),
                ('critique', models.IntegerField(default=0)),
                ('mort', models.IntegerField(default=0)),
                ('guerie', models.IntegerField(default=0)),
                ('degre', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('valide', models.BooleanField(default=False)),
                ('supprime', models.BooleanField(default=False)),
                ('vu', models.BooleanField(default=False)),
                ('region', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='map.Region')),
            ],
        ),
    ]
