# Generated by Django 3.0.4 on 2020-06-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20200605_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='date_validation',
            field=models.DateTimeField(),
        ),
    ]
