# Generated by Django 3.0.4 on 2020-06-05 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map', '0003_auto_20200605_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiqueregion',
            name='agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CentreReception',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField(max_length=50)),
                ('numero', models.TextField(max_length=20)),
                ('adresse', models.TextField(max_length=20)),
                ('region', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='map.Region')),
            ],
        ),
    ]
