# Generated by Django 3.0.4 on 2020-06-06 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_auto_20200605_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='lang',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='region',
            name='lat',
            field=models.FloatField(default=0),
        ),
    ]
