# Generated by Django 3.0.4 on 2020-06-06 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_auto_20200606_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='ArabicName',
            field=models.TextField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
