# Generated by Django 3.0.4 on 2020-07-05 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('titre', models.TextField()),
                ('description', models.TextField()),
                ('typeNotif', models.IntegerField()),
            ],
        ),
    ]
