# Generated by Django 3.0.4 on 2020-06-19 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coronawatch', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoInternaut',
        ),
    ]
