# Generated by Django 3.0.4 on 2020-05-15 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField(max_length=20)),
                ('suspect', models.IntegerField()),
                ('confirme', models.IntegerField()),
                ('critique', models.IntegerField()),
                ('mort', models.IntegerField()),
                ('guerie', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CasSignalee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valide', models.BooleanField(default=False)),
                ('supprime', models.BooleanField(default=False)),
                ('vu', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('media', models.FileField(upload_to='')),
                ('commentaire', models.TextField(max_length=40)),
                ('region', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='report.Region')),
            ],
        ),
    ]
