# Generated by Django 3.0.4 on 2020-07-02 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('map', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasSignalee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valide', models.BooleanField(default=False)),
                ('supprime', models.BooleanField(default=False)),
                ('vu', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('media', models.FileField(default=None, null=True, upload_to='')),
                ('commentaire', models.TextField(max_length=40)),
                ('region', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='map.Region')),
            ],
        ),
    ]
