# Generated by Django 3.0.4 on 2020-07-04 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('map', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CasSignalee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valide', models.BooleanField(default=False)),
                ('supprime', models.BooleanField(default=False)),
                ('vu', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('media', models.FileField(default=None, null=True, upload_to='')),
                ('commentaire', models.TextField(max_length=40)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cas', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='map.Region')),
            ],
        ),
    ]
