# Generated by Django 3.0.4 on 2020-07-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cassignalee',
            name='commentaire',
            field=models.TextField(),
        ),
    ]
