# Generated by Django 3.0.4 on 2020-06-06 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_auto_20200606_0238'),
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cassignalee',
            name='media',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='cassignalee',
            name='region',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='map.Region'),
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
