# Generated by Django 3.0.4 on 2020-06-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cassignalee',
            name='media',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
    ]
