# Generated by Django 3.0.4 on 2020-06-03 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20200601_1511'),
        ('report', '0002_auto_20200603_2036'),
    ]

    operations = [
    ]
