# Generated by Django 3.0.4 on 2020-05-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
