# Generated by Django 3.0.4 on 2020-06-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='media',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
    ]
