# Generated by Django 3.0.4 on 2020-07-05 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etatSante', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etatsante',
            name='url',
        ),
    ]
