# Generated by Django 3.0.4 on 2020-07-05 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etatSante', '0002_remove_etatsante_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etatsante',
            name='poids',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='etatsante',
            name='rythmeCardiaque',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='etatsante',
            name='temperature',
            field=models.CharField(max_length=20),
        ),
    ]
